import type { ToolHandler, ToolMeta } from "./types.js";
import {
  listChannels,
  getChannelDetails,
  createChannel,
  createThread,
  pinMessage,
  renameChannel,
  deleteChannel,
  listThreads,
  deleteThread,
  deleteThreads,
  listRoles,
  getRoleDetails,
  createRole,
  deleteRole,
  assignRole,
  removeRole,
  updatePermissionOverwrites,
  getGuildPermissions,
  getBotPermissions,
  diagnoseGuild,
  listMembers,
  findMembers,
  getMemberDetails,
  kickMember,
  banMember,
  timeoutMember,
  untimeoutMember
} from "./discordTools.js";

export const toolRegistry: Record<string, ToolEntry> = {
  list_channels: { handler: listChannels, meta: { risk: "read", requiredBotPerms: ["ViewChannel"] } },
  get_channel_details: { handler: getChannelDetails, meta: { risk: "read", requiredBotPerms: ["ViewChannel"] } },
  create_channel: { handler: createChannel, meta: { risk: "high", requiredBotPerms: ["ManageChannels"] } },
  create_thread: { handler: createThread, meta: { risk: "high", requiredBotPerms: ["CreatePublicThreads"] } },
  pin_message: { handler: pinMessage, meta: { risk: "low", requiredBotPerms: ["ManageMessages"] } },
  rename_channel: { handler: renameChannel, meta: { risk: "high", requiredBotPerms: ["ManageChannels"] } },
  delete_channel: { handler: deleteChannel, meta: { risk: "destructive", requiredBotPerms: ["ManageChannels"] } },
  list_threads: { handler: listThreads, meta: { risk: "read", requiredBotPerms: ["ViewChannel"] } },
  delete_thread: { handler: deleteThread, meta: { risk: "destructive", requiredBotPerms: ["ManageThreads"] } },
  delete_threads: { handler: deleteThreads, meta: { risk: "destructive", requiredBotPerms: ["ManageThreads"] } },
  list_roles: { handler: listRoles, meta: { risk: "read", requiredBotPerms: ["ViewChannel"] } },
  get_role_details: { handler: getRoleDetails, meta: { risk: "read", requiredBotPerms: ["ViewChannel"] } },
  create_role: { handler: createRole, meta: { risk: "high", requiredBotPerms: ["ManageRoles"] } },
  delete_role: { handler: deleteRole, meta: { risk: "destructive", requiredBotPerms: ["ManageRoles"] } },
  assign_role: { handler: assignRole, meta: { risk: "high", requiredBotPerms: ["ManageRoles"] } },
  remove_role: { handler: removeRole, meta: { risk: "high", requiredBotPerms: ["ManageRoles"] } },
  update_permission_overwrites: { handler: updatePermissionOverwrites, meta: { risk: "high", requiredBotPerms: ["ManageChannels"] } },
  get_guild_permissions: { handler: getGuildPermissions, meta: { risk: "read", requiredBotPerms: ["ViewChannel"] } },
  get_bot_permissions: { handler: getBotPermissions, meta: { risk: "read", requiredBotPerms: ["ViewChannel"] } },
  diagnose_guild: { handler: diagnoseGuild, meta: { risk: "read", requiredBotPerms: ["ViewChannel"] } },
  list_members: { handler: listMembers, meta: { risk: "read" } },
  find_members: { handler: findMembers, meta: { risk: "read", requiredBotPerms: ["ViewChannel"] } },
  get_member_details: { handler: getMemberDetails, meta: { risk: "read", requiredBotPerms: ["ViewChannel"] } },
  kick_member: { handler: kickMember, meta: { risk: "destructive", requiredBotPerms: ["KickMembers"] } },
  ban_member: { handler: banMember, meta: { risk: "destructive", requiredBotPerms: ["BanMembers"] } },
  timeout_member: { handler: timeoutMember, meta: { risk: "destructive", requiredBotPerms: ["ModerateMembers"] } },
  untimeout_member: { handler: untimeoutMember, meta: { risk: "destructive", requiredBotPerms: ["ModerateMembers"] } }
};

export type ToolEntry = { handler: ToolHandler; meta: ToolMeta };
