import type { ToolHandler } from "./types.js";
import {
  listChannels,
  getChannelDetails,
  createChannel,
  createThread,
  pinMessage,
  renameChannel,
  deleteChannel,
  listRoles,
  getRoleDetails,
  createRole,
  deleteRole,
  assignRole,
  removeRole,
  updatePermissionOverwrites,
  getGuildPermissions,
  getBotPermissions,
  diagnoseGuild,
  findMembers,
  getMemberDetails,
  kickMember,
  banMember,
  timeoutMember,
  untimeoutMember
} from "./discordTools.js";

export const toolRegistry: Record<string, ToolHandler> = {
  list_channels: listChannels,
  get_channel_details: getChannelDetails,
  create_channel: createChannel,
  create_thread: createThread,
  pin_message: pinMessage,
  rename_channel: renameChannel,
  delete_channel: deleteChannel,
  list_roles: listRoles,
  get_role_details: getRoleDetails,
  create_role: createRole,
  delete_role: deleteRole,
  assign_role: assignRole,
  remove_role: removeRole,
  update_permission_overwrites: updatePermissionOverwrites,
  get_guild_permissions: getGuildPermissions,
  get_bot_permissions: getBotPermissions,
  diagnose_guild: diagnoseGuild,
  find_members: findMembers,
  get_member_details: getMemberDetails,
  kick_member: kickMember,
  ban_member: banMember,
  timeout_member: timeoutMember,
  untimeout_member: untimeoutMember
};
